[server]
rules_file = "KaifRules"

[game]
hostname = "Kaif Station 18+😎 - Смешнее уже не будет🐘"
desc = "🌌 КАЙФУЮЩИЙ ПРИВЕТ, ЧЕЛОВЕК 😎👽\n\n👨🚀 Ты 🍃 залетел 🚀 на Kaif Station 18+ — тут 🛠️  мы 🌈 не 🚫 паримся, 🎮 играем, 🐸 угараем 😜 и 🐒 даже 🔨 переводим 🛸 Space Station 14 🌌 так, что 💬 мамонты 🦣 завидуют.\n\n✨\n\nФорк 💻 GoobStation? ✔️ Есть! 😂 Кринж? ✔️ Удвоенный! 🌮 Кайф? ✔️ БЕСПЛАТНО!\n\n🥤 КАЙФОВАТЬ НЕ ЗАПРЕЩЕНО 🍔 — это 🔥 не просто ✨ слова, ааа 🎆 стиль 🌟 жизни! 🚀\n\n💀 Заходи, 🌝 присаживайся 🌈, расслабляйся 🚀 и 🔥 пойми, что 🌌 кайф — это 🍕 все, что 🐸 нужно. 😈"
maxplayers = 100
soft_max_players = 80
role_timers = false

[infolinks]
discord = "https://discord.gg/jQnxNEv457"

[hub]
advertise = true
tags = "lang:ru,rp:high,region:eu_e,18+"
hub_urls = "https://hub.spacestation14.com/"

[ghost]
respawn_time = 15
respawn_max_players = 999
allow_same_character = true
allow_respawn = true