- type: job
  id: BlueshieldOfficer
  name: офицер синего щита
  description: "Выступайте в роли телохранителя и советника для VIP-персон Командования и ЦентКома."
  playTimeTracker: JobBlueshieldOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 90000 # 25 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 54000 # 15 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 # 25 hours
    - !type:AgeRequirement
      requiredAge: 21
  weight: 20
  startingGear: BlueshieldOfficerGear
  icon: "JobIconBlueshield"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-ntr-centcom
  canBeAntag: false
  access:
  - Security
  - Brig
  - External
  - Cryogenics
  - Maintenance
  - Engineering
  - Medical
  - Research
  - Command
  - CentralCommand
  - BlueshieldOfficer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: BlueshieldOfficerGear
  equipment:
    eyes: ClothingEyesGlassesMedSec
    gloves: ClothingHandsGlovesCombat
    id: BlueshieldPDA
    ears: ClothingHeadsetAltCommand
    pocket1: UniqueBlueshieldOfficerLockerTeleporter
    pocket2: PinpointerNuclear
    belt: BlueShieldShield
  storage:
    back:
    - Flash
    - BluespaceLifelineImplanter
    - WeaponEnergyRevolver
    - SecHypo
    - BlueshieldMace
